### ISSUE TITLE
Ignore extensions files

### ISSUE THREAD

**Issue by GeorgeJL** [songlibo/pagespeed-chrome-extension#8] opened 2016-02-24 09:36 UTC
Some chrome extensions (e.g. Appspector) load own .js files.All _chrome-extension://_ files should be ignored.

**Comment by songlibo** [comment] 2017-03-02 21:37
This should not happen. I was not able to reproduce. Close this for now. If you have an example that extension files are included, please provide details to reproduce it. Thanks.

**Comment by GeorgeJL** [comment] 2017-03-03 09:11
On time of posting the issue the Appspector was a valid example. It was removed from Chrome Web Store since then. But I was able to find another example [Wappalyzer](https://chrome.google.com/webstore/detail/wappalyzer/gppongmhjkpfnbhagpmjfkannfbllamg?utm_source=chrome-app-launcher-info-dialog). I my case it attaches file `chrome-extension://homgcnaoacgigpkkljjjekpignblkeae/detector.js` to every page. I your install the url will be a bit different.

**Comment by songlibo** [comment] 2017-03-03 14:50
I installed the Wappalyzer and tried a few sites, but did not see any of the extension's js was included in the pagespeed analysis. Can you please give more details? What site did you try to run pagespeed analysis, and what rules include those extension's js files. And what version of the pagespeed extension are you using, what is you Chrome version? Thanks.

**Comment by songlibo** [comment] 2017-03-03 15:47
Ah, I was able to reproduce this with another extension. A fix is coming.

**Comment by songlibo** [comment] 2017-04-25 14:07
Fixed in v0.0.1.6.

**Closed by songlibo** 2017-04-25 14:07 UTC
Labels: bug
